import nodemailer from 'nodemailer';

export async function sendWelcomeEmail(userEmail, userName) {
    const emailUser = process.env.EMAIL_USER;
    const emailPass = process.env.EMAIL_PASS;

    if (!emailUser || !emailPass) {
        console.warn(`[Email] Credentials not configured. Would have sent welcome email to ${userEmail}`);
        return;
    }

    try {
        const transporter = nodemailer.createTransport({
            service: 'gmail',
            auth: {
                user: emailUser,
                pass: emailPass
            }
        });

        const htmlBody = `
            <div style="font-family: Arial, sans-serif; color: #333; line-height: 1.6; max-width: 600px; margin: 0 auto; border: 1px solid #eee; padding: 20px; border-radius: 8px;">
                <h2 style="color: #2c3e50;">Welcome to LexGuard AI!</h2>
                <p>Thank you for coming to my application, <strong>${userName}</strong>!</p>
                <p>The content in this application is generated by AI, so please verify the results before using them.</p>
                <p>Best regards,<br>
                <strong>Dheeraj N</strong><br>
                📞 9063163226<br>
                📧 <a href="mailto:nadimpallidheeraj@gmail.com">nadimpallidheeraj@gmail.com</a><br>
                💼 <a href="https://www.linkedin.com/in/dheeraj-nadimpalli-a10257333/">LinkedIn Profile</a></p>
                <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
                <p style="font-size: 0.8em; color: #888;">
                    <em>This email is automated, please do not respond. For further verification, you can directly contact the admin using the details above.</em>
                </p>
            </div>
        `;

        const mailOptions = {
            from: `"LexGuard AI" <${emailUser}>`,
            to: userEmail,
            subject: 'Welcome to LexGuard AI!',
            html: htmlBody
        };

        const info = await transporter.sendMail(mailOptions);
        console.log(`[Email] Welcome email sent successfully to ${userEmail}: ${info.response}`);
    } catch (err) {
        console.error('[Email] Failed to send welcome email:', err.message);
    }
}
